// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOvw0zYsJAT9LIj8L00cVUshck6z-Y2pI',
    appId: '1:445811975881:web:58daa6fecbd65a8cf6cf18',
    messagingSenderId: '445811975881',
    projectId: 'my-database-be7af',
    authDomain: 'my-database-be7af.firebaseapp.com',
    storageBucket: 'my-database-be7af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_APA49pUnl81wG2-KZZG2JOxb8MC2Vs',
    appId: '1:445811975881:android:db672a69814e0827f6cf18',
    messagingSenderId: '445811975881',
    projectId: 'my-database-be7af',
    storageBucket: 'my-database-be7af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPHFI96Yjw3f4lRenqkWt8nKl0efWhoP0',
    appId: '1:445811975881:ios:767dd3516947060bf6cf18',
    messagingSenderId: '445811975881',
    projectId: 'my-database-be7af',
    storageBucket: 'my-database-be7af.appspot.com',
    iosClientId: '445811975881-2otcibta4h03d4htl63292qsohtjo900.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDatabase',
  );
}
